// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.StateBoundaries
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("features")]
        public Feature[] Features { get; set; }
    }

    public partial class Feature
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("geometry")]
        public Geometry Geometry { get; set; }

        [JsonProperty("properties")]
        public Properties Properties { get; set; }
    }

    public partial class Geometry
    {
        [JsonProperty("coordinates")]
        public double?[][][][] Coordinates { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Properties
    {
        [JsonProperty("gid")]
        public long? Gid { get; set; }

        [JsonProperty("arealand")]
        public long? Arealand { get; set; }

        [JsonProperty("division")]
        public long? Division { get; set; }

        [JsonProperty("intptlat")]
        public double? Intptlat { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("objectid")]
        public long? Objectid { get; set; }

        [JsonProperty("areawater")]
        public long? Areawater { get; set; }

        [JsonProperty("intptlon")]
        public double? Intptlon { get; set; }

        [JsonProperty("oid")]
        public long? Oid { get; set; }

        [JsonProperty("funcstat")]
        public string Funcstat { get; set; }

        [JsonProperty("centlon")]
        public double? Centlon { get; set; }

        [JsonProperty("stusab")]
        public string Stusab { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("statens")]
        public string Statens { get; set; }

        [JsonProperty("centlat")]
        public double? Centlat { get; set; }

        [JsonProperty("basename")]
        public string Basename { get; set; }

        [JsonProperty("mtfcc")]
        public string Mtfcc { get; set; }

        [JsonProperty("region")]
        public long? Region { get; set; }

        [JsonProperty("lsadc")]
        public string Lsadc { get; set; }

        [JsonProperty("geoid")]
        public string Geoid { get; set; }

        [JsonProperty("geo_point_2d")]
        public GeoPoint2D GeoPoint2D { get; set; }
    }

    public partial class GeoPoint2D
    {
        [JsonProperty("lon")]
        public double? Lon { get; set; }

        [JsonProperty("lat")]
        public double? Lat { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
